### ISSUE TITLE
Speed to the Website

### ISSUE THREAD

**Issue by Pratul1997** [MozLNMIIT/LNMHacks-2.0#2]
Currently, the Website is made on Bootstrap, and some classes of Materialize CSS is used but specific classes are extracted to pk.css.

Need Some improvement in current Speed of the website.

**Comment by GudarJs** [comment]
May I help you with this issue? I'm experience optimizing css and js code.

**Comment by Pratul1997** [comment]
@GudarJs I will be more than happy if you contribute to improving speed to the Website.

**Comment by GudarJs** [comment]
May you assign the issue? I will working on it tonight.

**Comment by Pratul1997** [comment]
@GudarJs We would be glad to have you along with us on the projects.
