### ISSUE TITLE
Bootstrap card addition in Sponsors

### ISSUE THREAD

**Issue by Pratul1997** [MozLNMIIT/LNMHacks-2.0#29]
Hi,
We need to add the bootstrap card to each to the sponsors, and the card gets highlighted when hovered.

**Comment by hardikyjoshi** [comment]
@Pratul1997 I can help you with this, however, I was having a query, by "bootstrap card" do you mean [https://v4-alpha.getbootstrap.com/components/card/](https://v4-alpha.getbootstrap.com/components/card/) ? I can add the highlighting effect on hover meanwhile.
