### ISSUE TITLE
Need Png format of Images

### ISSUE THREAD

**Issue by Pratul1997** [MozLNMIIT/LNMHacks-2.0#4]
As some of the images in different sections are or JPEG or some are not transparent.
Need all images in Png format, and all images transparent.

**Comment by MalemScha** [comment]
It would be better if you use SVG format... Since
* It is possible to scale the SVG images.
* They can be created and edited with any text editor
* The print quality of these images is high at any resolution.
* It is possible to zoom the SVG images without any degradation in the quality.

**Comment by Pratul1997** [comment]
@MalemScha 
I agree with your suggestions but as you can see on the website that most of them are in JPEG or either PNG format.
So, I would require some more time to convert all the images in SVG format.

**Comment by joel-g** [comment]
Working on this

**Comment by akashsara** [comment]
Done with this. Refer #13

**Comment by Pratul1997** [comment]
@akashsara @joel-g 
Thanks for your Hard work.
@akashsara There is git conflict in your PR, kindly keep your fork in sync and make sustainable changes.
