### ISSUE TITLE
Arrangement of Images for different sections

### ISSUE THREAD

**Issue by Pratul1997** [MozLNMIIT/LNMHacks-2.0#5]
As the images in different section are sometimes not in a straight horizontal line,
Need some alignment in terms of images for different sections,
Note: Mobile view should also be kept in consideration.

**Comment by reneesandefur** [comment]
@Pratul1997 I'd like to give this a shot!

**Comment by Pratul1997** [comment]
@reneesandefur Thanks for trying, We would glad to see your PR after sustainable changes.
