### ISSUE TITLE
Suggestion in Website for Rajasthan Largest Hackathon organised by Student Community.

### ISSUE THREAD

**Issue by Pratul1997** [MozLNMIIT/LNMHacks-2.0#6]
Kindly view the website,
Suggestion for the Hackathon Website in any format is highly appreciated.

**Comment by ashvin-godbole** [comment]
in what format do we give suggestions ?

**Comment by Pratul1997** [comment]
@ashvin-godbole Suggestion for improvement of the website in any way, except what is listed in issue is welcomed.
